Bug fixes marco
Arquisoft/wiq_es6c pull request #90
Opened 2024-04-04 20:18 UTC by marco-qg

2024-04-04 20:25 UTC, marco-qg commented on .github/workflows/release.yml
He añadido los tests para el despliegue.

2024-04-04 20:26 UTC, marco-qg commented on gatewayservice/gateway-service.js
> +function catchAction(error, res) {
Una función para hacer la acción de dentro de los catch(común a todos)

2024-04-04 20:29 UTC, marco-qg commented on questionsservice/questiongeneratorservice/questiongenerator-service.js
> +    }
De esta forma, si el servicio de almacén de preguntas está caído, no se añaden pero se puede seguir jugando.
A lo mejor se podría hacer la llamada sin almacenarlo en una constante, pero imagino que está así para usarse en un futuro.

2024-04-04 20:29 UTC, marco-qg commented on storeQuestionService/store-q-service.js
He añadido un mensaje de error por defecto.

2024-04-04 20:31 UTC, marco-qg commented on webapp/public/index.html
Con esto se indica al agente de usuario que usamos el modo oscuro, arreglado en parte el bug de #85.

2024-04-04 20:32 UTC, marco-qg commented on webapp/src/components/Button.jsx
Arregla la issue de sonar cloud, #88.

2024-04-04 20:32 UTC, marco-qg commented on webapp/src/components/FirstGame.css
no se usa

2024-04-04 20:33 UTC, marco-qg commented on webapp/src/index.css
> +
Elimina estilos añadidos por el agente de usuario

2024-04-04 20:34 UTC, marco-qg commented on webapp/src/index.css
> +}
Termina de arreglar los bugs de #85.

2024-04-04 20:35 UTC, marco-qg commented on webapp/src/userStats/css/Game.css
Ligero ajuste de borde para hacerlos redondeados.
![image](https://github.com/Arquisoft/wiq_es6c/assets/145330494/5018cfb6-c416-4cf1-bc6a-731afc1e8521)

2024-04-05 07:23 UTC, AbelMH1 requested changes
Detalle

2024-04-05 07:23 UTC, AbelMH1 commented on gatewayservice/gateway-service.js
> +  else if('response' in error && 'status'){
```suggestion
  else if('response' in error && 'status' in error.response){
```

2024-04-05 07:31 UTC, AbelMH1 approved these changes
Todo parece corregido correctamente

2024-04-05 07:41 UTC, merged